- name: Deploy Calculator Container Using Docker CLI
  hosts: localhost
  remote_user: akshar
  become: yes
  tasks:
    - name: Pull the latest Docker image from Docker Hub
      shell: docker pull akdev6298/scientific-calculator:v1

    - name: Stop and remove any existing container with the same name
      shell: |
        docker stop dev-cal || true
        docker rm dev-cal || true
      ignore_errors: yes

    - name: Run the Docker container
      shell: docker run -it -d --name dev-cal akdev6298/scientific-calculator:v1
